apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: application-stack-intro
    app.kubernetes.io/part-of: app-application-stack-intro
  name: application-stack-intro
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: application-stack-intro
      app.kubernetes.io/part-of: app-application-stack-intro
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: application-stack-intro
        app.kubernetes.io/part-of: app-application-stack-intro
    spec:
      containers:
      - image: nginxinc/nginx-unprivileged:latest
        imagePullPolicy: Always
        name: application-stack-intro
        ports:
        - containerPort: 8080
        resources: {}
      serviceAccountName: default
status: {}
