apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: application-stack-intro
    app.kubernetes.io/part-of: app-application-stack-intro
  name: application-stack-intro
  namespace: dev
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: application-stack-intro
    app.kubernetes.io/part-of: app-application-stack-intro
status:
  loadBalancer: {}
