apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgB7oojjFcs91IK1TK5KaNu5F+tBpO5O8TjU1fdQTC5xT1lZX+4Ww+E6uQq6GKJOCm6wmJYjQT6GmafYEYAeZfpaxAwK1yarDQlUkN1JtIO0EbCJMew0dQ3HiTiIJACTkQYD0kK1rYxR930sqyZMP6u1tii7YanGSXpRCIZ5RKp23VXILWVnM4CL1+N81YNpLNT3xvmVKWs/AffEElLji3ZBC8e0nWQhj0fTpk1mFBm4Tn4obx2W7AfX8c6rs/UP7syfJSqrgSoTAQxIuwFIIsRRTkQ6jp348LzdD3NBC2wVQXVnhMdoGz3c56NHY+s3+YXONdlYKLI6s74f6hi4E/OyqHY6tNwlBr/RLYyJKeQBYSKcX/1SghZL5H94Z31PsvxNychGofuRzOVcgaNE4fwa2KkqIbseed9vkdsds0lM82+RiUsGiyuIK4t0bmRKRCzh+Nd2K0EpmfpqRW+4a8uP8IWjGb0v2s6LYGVzXABGKjH0t0QI4E9oBHrn7jdwF2WLWoPzIfb70mpocVCY4f51w0cFY4FdxvfY5S6T0gNAs7vRTRrnvy65eHbUyjVajS/OjsH+92Hinwtbi6qLguF5gO15NzYWt0vwEa7o5gy9ELAFz1iRgkHz8g96RfUbrDdXfPJmUs9GdLS5lG8gmP2TeZpz3HhLGA6nKUK5Vk4UK76NHSYHiPEpcFz+0CgbuN9gkLFmKHpCbGGVGrq4pQ2/wj0CDmaJQftSzjdXG+icPldED4/lWzuoRHMaL+Jf/j7nebRreNv/mUJj6p71fEpbzjT4vQfzqk9J8HTWMR2QMScgscdc5A5dqPknEcjTGJ/myhthbOjoKpma3nI1BOY2uv7NNOkQDkJIPHdlnzKU9GKZAsmXaQbDp7hmy1582odNeNaX+dXGsmjkYolHkr8=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
