apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgBzNpBHkxF+e8Pl4ufH8FhWL2/aeqVmtYEY1fm3N1/fvMw3e/+Zj8BFzzuwG5NC86asnyl1idw638v2GprypU06SWqbSOv19LAL24p4maAWt4JcagNHT73PNR0J5zA6YpIhLGBkqcP96sApsjdlqGu8Bt1iD5gGdc4R5yCal+fZff0ioQMa7yxT60Vg/FMovUxAHMvfBYwefEWIIrDFPrRbjK4WFtgxabRUl00O1TA89f2D6MAEGgNHWMUTVQkKql8xqTjjBzqgSHEX0LEpeu3YmAyzln2PO8SlZvsAEMgQsPOWDkZ4Re243hGyqtKUEopYmZ7+lnrlBNKlTUFqfh84wNASpwOMRwNKFId6CAbmE0ropX4SKEPg63bpB/nLegii99fo/NmAuZ5XaVnB8dUlwydK8Cma2nxfjJ4kdGAFIB9GMMNbU1+bTAQ9aRabPjYDnG1Ey4BS/RTvjV9OIkFyC2lG2LBnT+/k23bCq9xVOKCZPnUjW8A/7yZsyBxIj2i6LhqDWOafWHlbGMygZRUJhtonY2K2huSMHe1HsnwQbSCLbixe1yzXtbIOt6a+L5MI7qubbmQ5fNgb4CiNTfcpjLrBcTTJxx682mAJ466aZO1X/cdVBNoIEmAlaQxuLdQfk67bhEjzL9ZtAkD0SeV/QDREBTvufyZf61NYRLxp5PCTQMlwRxs9A+kOvUqHN+H3l8Qw6Pjsf5MSKvKdcZQn17kz+RYDYwAWcJ8qVtZtlv6Lrwx6gxyiJscr8glV1QbIlu9Dxnq/K7yirUNFUcXiiKZ/jXseRjvzzPzpZDDflks8QveAeHvqd+0PCbTQUVT86tbBZI6ZmncxLXoN2Gt8lIzWGlZsMVSmjCmk1gkDw/nPgtCP8+jH2Se8NKmxUBHhHSEC2+eu8Rq7piQ9CE8=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
