apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-access-token
  namespace: cicd
spec:
  encryptedData:
    token: AgB6a51qGPktVIwB89jNKlsyiylDPEHDTtCKetYgCzsq2hjrUjLCFU9hjPkHZLuqSMD8HXnkHKiFxeRaDWCuhLuzECqVUBcVHk47roRQPbHmBYIbyBGezoE13WI9qUZemhgk7naF6ImL921NZru57tvevwLsUHVtpYfbGELohq/3X/sQLaSOSb1wMGwiy46JZGmu6fJiC99P8wu/TekDmW2HGGXOO8vDCMIZgrpy4IlBATX2l0UhsIX/NMT/tSreunFGDE1yN3vaZxzYRwowTunIGhpRRD3zwMWHY9UbDSP98DXd1uY6YHV4iEZBq8vRd2m8WKjLuQz3FYbhBCOM3jEHW0KoSfiNwPXDXgQWqfMop5dDIRDozIEZUH9P7LRhQ5JTSA2bPKpEykPj0tB8m7qaNG92NOkZMnhBh4Vvff/z8DRaLrfAnjRSP35IIL4mnlj4f1XYgPChQJpWX4VuqQG6L5EDCDj1wHiZ3VF7ODp1idFVpBPCtw7GEcRHiDHwjRU+2VJcwEwNQ+gCzoilBQDz7EyJeGUbl0Mk4lAKnE4dZNGqTi+yFyLXwKQUga2m6hPIA8Nk5k51RJKQmfUH0o5ADiihP6yKi+GqDylzREOK1xKyjLS+VZynhSrGVD+DrxyM56zueSBZc47KOh8Sn4Zq4DTly8d39OiD9S+OFpavLGe6VY2Z2EaNZvSMg+h93riA6wMJRYb0OVgKAXnm+AVC65L6IeCEx+faEj7LXr0fb1MpfM4BStoA
  template:
    metadata:
      creationTimestamp: null
      name: git-host-access-token
      namespace: cicd
    type: Opaque
