apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-access-token
  namespace: cicd
spec:
  encryptedData:
    token: AgAkai3SZ4BlAxCYhjSIuPg7lIYsZ5pFNBb3dtaIzmsyxRytpnu8NTPxCf56b05lyKx/7LbRINc5AphCTAxudpsAWO0OKADeglM9wwJblr6OSBcjbs4W7ldO7yIsAraShpOoJkAfS1sj/MqN+6NumAhCnjbJGPBrETgTlOx8SdwsmJJz+8VPOF77QYEsYTTxkxb0Je/zWmmqXo5IL7iHRm+TTyNDGb/hWFI4IAkfaKn8OlMbM9cKMG4npa8Pv0kwE1NGVwTKqG0NZx7xqQsCwnElF7tfPVYgURrjpg+vFlyDopOWirIKrhJob4V+v6i8+FJ+Km6KJtzRcmZHPmfMjB4UC/iZcrSmG6ci+DDnajurctIdqMdeATB8B7pjPO9u/TPB+RbD7CtLeK07Z6DRNszcPfEnJigy2XvUfvnBftaYSTCZifmzxeF+WqjDYdYZDAjLLcvlSjzcEUz07HSJgJiv+ykyeNhFDAuG/lf9iPSGKkSbck41mvFEntZo8H1XVmS5RKylZnyvE82zfbIEZV1BP/i8SFJRZPgaPDIcB+oBEYD4lk8CiTFzpelib6O0z8anRSjJLPhlPY8YGVNUNDdfjO8wcA6AERFrIRIY9C9HNWmzKsDta3dNcsb6LQj+jk1OIGDQL9dlssI6Hx4SmaS06hcIUToMYc9p/x9F1SmDJPNcTWbczJYDKQo0CxzPWRDDmiSOBvZ0Ib9AJZF+0Ann43Wy/GwpCrd5zFrImCaVEMFrn3CEcgpK
  template:
    metadata:
      creationTimestamp: null
      name: git-host-access-token
      namespace: cicd
    type: Opaque
