apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-access-token
  namespace: cicd
spec:
  encryptedData:
    token: AgBY4JU8vs8C902q4TgZ1Wm+ZCCnl85YyblGmib/jQcXOA514TXtUt5JeS/DQDnURc9Kbqtf6RGHb6bKpx6375oss8PMf1a40YduvKCtFYmOy4Voyq4NzLv9zyVWCM/+VPcEVZFI74XoePLAVcTsfIOOpqrpb5YpADMBVZB59Bzxx2eM5rKacOc0q/dRp6XA7lQM4B9GZtLkcZqqDbvOatomdpKRkElSYbqThM3iTxQyErjKaXMC3jrf31oJTRlRANYWLsb+xtikIYUm7OWEKZTenQICfJdonQqrFLbjKySpGYfUuorm/LD/XfBgsg8DFwz7K+hyJRVconNZvAcbqWnmMFsrEM1IKtLIq6+CyHvWdIXzCexSyGKc2jPjwz8DEji7AZmtuDyTYyysc4M467ao4Puo90bFtwSejc8zRE+ik2aOKKNmJZ+uORUhpAavQBdlU0O0nIx2vXSWGGMAGYr+ZUp5nuFClEkromDt6wjqVSakPZfHqg/pJJC7FcdK/PzcZlftPV9mKHs9LDvKQdHj6MZrxVzfk5dma/OFcmfzAF3GILBw2VekFs9PP1jrqtXRkTGAltukYUeE81S6Nr0zfYwC/afbX//Jzg9H3ivv6LSAkSVxpcKBDybR6ADyDkYxKp9AlO9hF1IvCN0+BgJAFPCVKTb1MnlJgfgMUDUXTecrdoR1lAMT1u/ektgZQASC9w4vZx9Tq8R5WbMthiOqR6F/mPZQiZ/+m5Q1XunFDq38XOJHxa8f
  template:
    metadata:
      creationTimestamp: null
      name: git-host-access-token
      namespace: cicd
    type: Opaque
