apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-basic-auth-token
  namespace: cicd
spec:
  encryptedData:
    password: AgAOV19sJeOyPqQd+KwPxINMGcUePNRs2TqDKSig4RRUrc9VVLDA4qW/xd8PdLt/uz+3++aVWEwmYNizZtypRtX/Sb2NTalQnY7v1EFAjMXL9ecENRGLFIKYly6UV8dU0Q3dpDL6T8kSGxCzZKEWanfPZzSGAlG2gXiXX0OlGAx6BeWcjlLBYt6h5trc2K05OEZk3EowM0rjB7XMUK5m/eFQ1y/76g5NAhA37OTHxfBGC07xv7Nx82hAuaBoCbuWQ2aGYV0lqZceaB4aig5PPiCtoNVqW9TQIJlvhJP31NFcIPGN1YmkRQaLt6csQfyfj61OW7AS/4lnyplxEaaSkUbNpqipYPdizl83hkE5dbpW0Zp3jChdI3zliy8NgyR486Sx+GCp8yxHBHPJKDDddXaY63Te9ySFVX/+/+kpRZetqgjdiLTKIWuIUZKe8iZ5mSzY36OakmmvaF3YndtGQFHQWpaI6qKpzzOJHtg/OYX2+wAobIdfb5qxFccNocvbUlmZZ6HkgiIVU5HHiwfr9UkqjmtGKordJhbkGUBPbyaFxTIhRzTe8ZjPHoOnj7XNnpIB7m2CwKCFmheLvCqL9KfYbGNh7XWotm0T5miJlo7RA95HUXSl7qxvYS/j8WpeqYhXKNwbYR4TE/fQa2CTFA13TIMmIKwmcNxZic+QR8AYpst7oDX+CmKlaajpjMuxUx/GKbjOkLqS8MH2lR15lxB0pFaEDqmZIYMF0zZvRlU3S6FSUC1JAFA+
    username: AgBcCGQLzsdBKqFkBYnoeOJQ6hFDjGUdtsN1vtfG4Pd23suhmolTiQ98WtkCelC4WnMD97NbilmvafTthfxfKfoIDQn44eqozw5FdOytEgyKjRKouEbESg16OQzZ9vRnk+DiG5RY4p3a8r9Nx7B+IufpatIDad6oUidc85loWH4AjbPIreWsDV43Qmu6DCuayzvz6YPcFDa7uMJwr+xBS29DmNVO5vpsAjK7ynacExUw8rpplmmpdqei3VsB0ucjZqLLTVivUlSIi6SGH6hCP5MCDHJtCmzdZ+CKfFGHKg6ObafJAcV4ExDH+LOD1MDahvlcb8Pfvoc5jxbVVzlfwltpNLC3a6w5/uh4JmEgW9bc+8RYpekORl33yZLnLkOeG1xM9Yiq2oUU77ki+uS0BtWa1EMu0UXtgxljodikcp+/sbT1uK49Ea0T4DUuicgsCzqpTkFV4456IbPChu3ijeDBUXxV8M600Xj2cH2MyEC9xJ/EbFFcDZmWD6EWwQ5nw/55ju2Uy5jILOYGgfQBnr2FgZMaZUYdFL04LJWMaGop1qWxz+f8Ck9z19bdfg68Sw42hCBdiUgJmc068nKe8ru5ZpvQB0vyVbGyRRqKZfV2AA32t4t+e3XND1cqjXaGYuERA4mVxvTFI6WFQfZTeIbdiq6ZsA6ygZ7OLZgKEq9PLzNsZz7j9ezHYopxGn6FBJ+qhLR51wg=
  template:
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-host-basic-auth-token
      namespace: cicd
    type: kubernetes.io/basic-auth
