apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-basic-auth-token
  namespace: cicd
spec:
  encryptedData:
    password: AgAZxLfv+obouc0f7acX59kKqwzj3Z8r/jrMjMd/5oXfMBYnuNJn+XfBNF71AtrWyKCipuIH/l51vBeL1O1HMLjoSIypd7x6MsWwepG/WJz5EV9/416o58dOs1mTBtA8XKWXyqYwRPqXvrXCXDtLWiDs4bNjJ1LbJiuqKxCDgM7J/PfK0lMsTslpS7CpXTEiuV3YeIt3Ef1wDzXh6myRWXvgbvoTwLgk350qCqjkmLw0ZmE42RFVINq3YVC9Xp3J4AfkBjav7+RMRVQ/4A784mMTtJnNGbUpQCH0JFYW1lzi67Z3Hh8DTRc8tqoEHTTEqyAlSBqAW+sH2FBnMNnnHE6/xWe//KpQjPTcUW3myN4jdt3k+iDw6/t7WK0fJQ9g5ejBoQmedHyoToQ53O33iqhZyd/52nYldACThXIIwS++KIqssCKqlhp0Yu+c71LEQge8VWL5BWCjkVR+s3cFO5plqBsx7aM0l8mlyU9Lf+QOADOu7ggqlXzl8zc2NftOVcExMXhvQoaDp/c+wB+2QO3jnL86I5K9+wyNklgndy9XosieCtr24Kl1uVn1yd0wx/qdBRj+SJH3EY/r4z3ic9DfndW4zl5rZyRG2gxoRZ4F0zJbJhllNVruofGrqJWJqcYZD0dS+VndxObj6jByF9EHITE0db3SB9/u+BtCNRf1oY3T99tsO8ghyE0QgdHFUnvU1+V+yLPrUV6iiRiIA7UtXNwG2/zGIUA7QT8h3Kl2UQY/tkYWjz5y
    username: AgBdKgiqYlsI4wfBLW0EYauHE1gP9wILtkRTJPDBg9UE7AYUhXHwUhOxs90JbuZ2cKNr8ZYN1Jvu0SEXbpWNFAwNCdlnfq1tSckfVR8H41lvzTcMtPmYav3GpzNtyO4OCDS2o15qI0jdyJIDX+pGtB2/5wpIQHrXHerm5JrYp4LWDyA7VRj6v5e6nwGa4wi55GPVnOUfH94Ln6eylaJm9dOUVNp8zsC8v6XmYF+bEXj3kcCiO49n0msp1jHoKBhf4gJ6ZxaFcX2K1sbumAAYnTQL+1TQG9pPoIX1+7bsqlNtnRvPI2xho4HluUGFC3zTKfCVmzv5mNGcu4nFhl/4dcjStdVfBcVP5caTgDSh120xncj8prddqsHkmOAjhOrfOh03QNeaGOP02tARz3bbCOaUEQRkXRCd4OlCzUfQMls5uwggm9mdWzVlrLYZ7NiY3aRgVZZJHM3g4JNHFz/3EZO0EygsWu/eEKlt+tbh7t2UE2mX7jmveIHB01UuaHu4RzbfHfkocSvCp86eOb6FLC5+8ftrciNudSicJ0b1L5S/QS1puRRjtAV2vwZOldX7vqdG4PyMj19ul1oUjqQXNxgUzJhcs/+XUJAmPm5MpsN8A6Zei7gvG8TeCVN/BGdmmnXJl5Zem3FzXtAgL2RbIuXkp1D0GRWE5ERn6YlU0sCaFz2OYYBeMn5IwWHbSm+LJiU1j+GFVT4=
  template:
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-host-basic-auth-token
      namespace: cicd
    type: kubernetes.io/basic-auth
