apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBOHkN4gLEGH5uqC0xSB96LK8cBByMhsJCny8NAj++PzslHPqAbEtI0vyVfmDI2cD7XrDY3ZT+ZnfPxGeRx4c2ge0Hab0DivyaBtzOpK87sfr3jNaaIlykfxIrbr8DIP+8Clz3R3w9vFrrQeIBbm+55wN+R19h01K4GSay3VE1TJzG1Ni9/ed4pGgO6kGZRD/oV30ZJ4Oon6qoBQDAtEMhMLitDS1vUoBm1yGQiZaWi6N1uUarA12n/5IrGEUeOg0uS4AO/QmdZ5SaAqPshk8W1E6MAfnNEcZFqnUel5+Yuq7n6eifaVtj1d5lWz0789Rca7LhWWAAJrJ11/0V5r3Sex8lCg8rJZ2PcXsoygDA0YNcgTe5yLByMRDjAe+rtjYs/Zr9lzobbUAAt8BMNoozUrmMzNLx2fUh3IuNhH81kB/y78Pp+RDyF+TqJ7jUmW+pQMpQso4pvtVIx4DwfwiQYPY1ro9EJxSEV3O2yBt6zImeb8mxQ1pw/VlnjOPm4a8kFNDjheFgV1FlbHVh3khwQ4wz0WQvIT2WE1OTVB7gSn8inzvq2XN+2OzOTvLIsHPkv0fiOgL/+InuO5VlFfXsfwidL0Cdd5g5FNOuijM4DJNxdPSA1sZYZEiRZjFAE9lASSjzzNvV0EIr635xAd+sn6+MH7H/TD1it7GfYyl3xXDVZbdbi0hHrZAn9N5t9lZIFu9QHiMgguVwaoZXA/RKaaHkJPA==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
