apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCLhZjNiTsCFRUimHjAm4JSu40tgb707kyB6yGPU0zz6VabeqwMB+ZQtVSIdUC1eH7jvyIRcrIgEUJvwo3j8fktZEVjL+w/93Su6XaDuh8ngOsy16pImQVuYP1fy47BL3sSCtYgKLjRxhPUVyTLlHBHkHdkgBG4FGYGbKoNSnX73y3vrCBqKscbM33iaUX0+ar2PJkACR35I9cbzdNxSh9WnFuIOJWez3Mzn1NwdtGxERxuKNdMMM79YyViA4y2cFie9Zk1dvp8Q8m5u0Yr6o4ZcebQ++z/5SoX5MAcnT1YGl7rz0UA6VpcMvRkR6Wny8l/Mb5USIhJ5G/g8v7s/rg68opfzUrbgQnnG0vvVv17v3PNPm43vWG+dmmf47G1vpOeOl3A2vsawjDeNm6SuoS3EdeYY1mcPetMnypj2NNrfhTCP6jRKBoRvkGHDb85NLrFxxfZ54lZtAJS55GdticnuD2Jz6Etydbg/GCyU/agyhYip6fVPNiVQoT6iylruwi7+eWzQwCeVMk5+NSK+D6nmvamD2wVFWIA9Hiz2i4f9pH5wZNfSktcmRgy21yHgvo/GO9jOkCCxR0e0RZet5FaN7o/xrRGHveV0zTqTodSXaLi+XtCXiipE58wyufX8uayha8kkv8M+J8OCylhncVihfU8S01SBaJNJ8qPeBIcTbfwz+FoXuFr1piepBp8WIx+QG6tbzqFJqEeNCQ7WtxRFDErQA==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
