apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCazGDZXqzENd+iinSbCrBUlZPNL08hfl/lbOkuZo1cayXHLFr2ybF8+1uDlrzAhRQXYoQbh8drVcdnEZLsoQUrUtT8U2npWdZQIOcDUjAsS0NDmD6nWWY40bzRLVVCn95nwEqZYNtPfaYrvSILycKJOqXxxVIYrp/3duI5JIjHa80YNERGdiKnipBJIL2sa9YTB3Se73lLNvE3NlpTwQY6IFP67dYu8Z9bzDk470wMBQAxxAEllg7kdpEwzzie2ltMtbGhYN+o1gqn6fhK6Zqt8f8x3s/AaeBhe2l9qaTvo3jc0hv891kexgOJcOEnTyOuL+FwqJM1cEW+0Z1tQ4gb5spp0LtBPn7j62A6dZLrFFlXxUnPSFrZP+oF77ndG8OP64HsQD/w1KNsZZ311UQITaPOyJYi7UznjYPLvc35Gqhoj6H83qHC1OH8T8JGrrGsfzYfZ9WsLTykFTF5aLxoCX3DZ1yd+0IIStolwUj4E+dhdJBmgsCZieWjKmFzY9YWxAJKCbEiraaez38qXBuu4WYUuO/CjlkXagtmgNBQXhTlR5sE4x9NG5P0qHdzUw3DbzEpaMOFE05V+5BXBNhid0GKMdRNvDvd+WnczTTz0tagge2ZhdJ1nTHQKXfxJ0DXqlt9+bV113sD3ZIf+04p3VXyYBFrHkTInRUnXBaSSR6JkNiZ0ADOQ1WmPmOqV3vhlVeW6nNZxe74Jum/EOocrxOhLw==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
