apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-application-stack-intro
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCtGr9uvVrb03txoLRUUB7n6CYKVq68oHIO6SWD8vIyXjdMoo664Bl1C8oFsRMXqfmygR0qXwkecRlm0bUrpsK+eeLqt/2dua+Q5iFg+pOKUBbAuklbI5s/RHpUbBDSYDcXi6MW2WUSX1znfX7PYNx8yuXFPQ/asucr7+Hty0KKL1ZyGBbtZuRRPLL1vkiWUjl3kfYIvGRZs8kcs6dMh6/eZBalO5UF+Zf4pUQNTPOGgQBWXgVNd5/YagZF2NfpFEO6CpaGBd4mZhV6olfYCZcZ3lgeiDEfSHCiCe117+EBB0l2KVBnuaG78t34hfLXnsNE9x20yLBQWMCkagq/r5NBkWBpeCz0pv/XQteAIdg6XMAHluuUuEFasVw1Ppk2Q2SjmqFQXCQEE5BbK7xkPtxmGOG/RyS3SowB+A7olKLKQr9MacyEnBvRLXBTomnteoTqrOuQMck3pXGXQtaCzJ/P+RZt5OYsSpgQXM8iBSZy+oAxqoDP03n3V4itHkShNn6FXCjGvXtnCV3t3bG3lUNBsh5RUgYGGYJIDBbvbvwvsmhPJRhFkIt9i8KNsOymulMKAehBLclqsZQ4O5GKCrNu7J0hqwj0liH8HzsNyqIRyg2fBjd4B7Ja3stwJz1JYw7iOEvjKYEEwCcsC5dTAuhXv6BqtH17WunZYJKsYmXB49aDHeP9KU9i4TYExDp/g6Tvw9z8vA4JQ3LZalio5Cq7Qg7TYg==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-application-stack-intro
      namespace: cicd
    type: Opaque
